/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Issues */
        get: operations["list_issues_api_v1_issues_get"];
        put?: never;
        /** Publish */
        post: operations["publish_api_v1_issues_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{issue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Issue */
        get: operations["get_issue_api_v1_issues__issue_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{issue_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeline */
        get: operations["get_timeline_api_v1_issues__issue_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{issue_id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance
         * @description Move the issue one step along the demo path.
         */
        post: operations["advance_api_v1_issues__issue_id__advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{issue_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete
         * @description Run the rest of the happy path: verdict, merge, release.
         */
        post: operations["complete_api_v1_issues__issue_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{issue_id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decline
         * @description The publisher declines work the review passed, with a reason. Once per issue:
         *     the work goes back for rework, and after that the merge or the grace period
         *     settles it.
         */
        post: operations["decline_api_v1_issues__issue_id__decline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{issue_id}/approve-release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Release
         * @description A named approver approves a release held over the organisation's threshold.
         */
        post: operations["approve_release_api_v1_issues__issue_id__approve_release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Loop
         * @description The loop in public: issues funded, settled and paid, for one repository or all.
         *     Built for a repository's watchers to see, so it carries no wallet or transfer.
         */
        get: operations["loop_api_v1_loop_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{issue_id}/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispute
         * @description The contributor challenges a rework or reject verdict: the same commit is
         *     reviewed again against the published criteria, and the outcome is recorded.
         */
        post: operations["dispute_api_v1_issues__issue_id__dispute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publishers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Publishers */
        get: operations["list_publishers_api_v1_publishers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Decisions
         * @description The append-only decision log across every issue, newest first.
         */
        get: operations["decisions_api_v1_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_api_v1_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contributors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Contributors
         * @description Public profiles. A wallet is never served next to a handle; see docs/PRIVACY.md.
         */
        get: operations["list_contributors_api_v1_contributors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contributors/{contributor_id}/reputation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reputation
         * @description What a contributor's reputation is made of: one event per settled issue, from
         *     the money ledger and nothing else. Public, like the settlement comment it mirrors.
         */
        get: operations["reputation_api_v1_contributors__contributor_id__reputation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contributors/{contributor_id}/statements/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Statement
         * @description One contributor's payouts for one calendar year, to file from.
         *
         *     A statement is personal: its settlement references would link a wallet to a
         *     handle. Until contributors can sign in it is served only by the simulation, whose
         *     numbers are not real; outside it, an operator exports it with
         *     `python -m misthos.services.statements`.
         */
        get: operations["statement_api_v1_contributors__contributor_id__statements__year__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publishers/{publisher_id}/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Policy
         * @description Replace the organisation's spending policy: a release threshold with its named
         *     approvers, and monthly limits per issue label.
         */
        put: operations["set_policy_api_v1_publishers__publisher_id__policy_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publishers/{publisher_id}/spend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spend
         * @description What was budgeted, committed, released and refunded in a year, by category,
         *     and the settled fixes to file for a security review.
         */
        get: operations["spend_api_v1_publishers__publisher_id__spend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publishers/{publisher_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit
         * @description The decision record and the money events for every issue the organisation
         *     funded, unedited, as JSON or one sortable CSV.
         */
        get: operations["audit_api_v1_publishers__publisher_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe */
        get: operations["describe_api_v1_webhooks_github_get"];
        put?: never;
        /** Receive */
        post: operations["receive_api_v1_webhooks_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnnualStatement
         * @description Every payout one contributor received in one calendar year, in UTC.
         *
         *     Built for a finance team to file from without asking anything: each line carries
         *     its date, issue, counterparty, amount and settlement reference.
         */
        AnnualStatement: {
            /** Contributor Id */
            contributor_id: string;
            /** Handle */
            handle: string;
            /** Year */
            year: number;
            /** Identity Status */
            identity_status: string;
            /** Lines */
            lines: components["schemas"]["StatementLine"][];
            /** Total */
            total: {
                [key: string]: string | number;
            };
            /** Payouts */
            payouts: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Simulated */
            simulated: boolean;
        };
        /** ApproveReleaseRequest */
        ApproveReleaseRequest: {
            /** Approver */
            approver: string;
        };
        /**
         * AuditExport
         * @description Everything an auditor needs about one organisation's issues, from the decision
         *     log and the money ledger, unedited (#52).
         */
        AuditExport: {
            /** Publisher Id */
            publisher_id: string;
            /** Name */
            name: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Simulated */
            simulated: boolean;
            /** Issues */
            issues: components["schemas"]["AuditIssue"][];
        };
        /** AuditIssue */
        AuditIssue: {
            /** Id */
            id: string;
            /** Repo */
            repo: string;
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** State */
            state: string;
            /** Labels */
            labels: string[];
            /** Compliance Driven */
            compliance_driven: boolean;
            /** Acceptance Criteria */
            acceptance_criteria: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Price */
            price: {
                [key: string]: string | number;
            } | null;
            /** Decisions */
            decisions: components["schemas"]["Decision"][];
            /** Money Events */
            money_events: components["schemas"]["AuditMoneyEvent"][];
        };
        /** AuditMoneyEvent */
        AuditMoneyEvent: {
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Kind */
            kind: string;
            /** Amount */
            amount: {
                [key: string]: string | number;
            };
            /** Counterparty Id */
            counterparty_id: string;
            /** Tx Hash */
            tx_hash: string | null;
        };
        /** Claim */
        Claim: {
            /** Contributor Id */
            contributor_id: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /**
         * ContributorProfile
         * @description What anyone may see about a contributor: no wallet, no provider reference.
         */
        ContributorProfile: {
            /** Id */
            id: string;
            /** Handle */
            handle: string;
            /** Reputation */
            reputation: number;
            /** Settled Issues */
            settled_issues: number;
            /** Earned Usdc */
            earned_usdc: string;
            /** Verified */
            verified: boolean;
        };
        /** Decision */
        Decision: {
            /** Id */
            id: string;
            /** Issue Id */
            issue_id: string;
            /**
             * Actor
             * @enum {string}
             */
            actor: "agent" | "publisher" | "contributor" | "system";
            /** Action */
            action: string;
            /** Rule */
            rule: string;
            /** Outcome */
            outcome: string;
            /** Cost Usdc */
            cost_usdc?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DeclineRequest */
        DeclineRequest: {
            /** Reason */
            reason: string;
        };
        /** DisputeRequest */
        DisputeRequest: {
            /** Reason */
            reason: string;
        };
        /** EscrowCommitment */
        EscrowCommitment: {
            /** Issue Id */
            issue_id: string;
            /** Contract */
            contract: string;
            /** Chain */
            chain: string;
            /** Tx Hash */
            tx_hash: string;
            /** Amount */
            amount: {
                [key: string]: string | number;
            };
            /**
             * Deadline
             * Format: date-time
             */
            deadline: string;
            /**
             * Released
             * @default false
             */
            released: boolean;
            /**
             * Refunded
             * @default false
             */
            refunded: boolean;
        };
        /**
         * FileableItem
         * @description One settled fix, with what a security review needs to file it.
         */
        FileableItem: {
            /** Issue Id */
            issue_id: string;
            /** Repo */
            repo: string;
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Labels */
            labels: string[];
            /** Compliance Driven */
            compliance_driven: boolean;
            /** Acceptance Criteria */
            acceptance_criteria: string[];
            /** Amount */
            amount: {
                [key: string]: string | number;
            };
            /**
             * Settled At
             * Format: date-time
             */
            settled_at: string;
            /** Github Url */
            github_url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Chain */
            chain: string;
            /** Seeded Issues */
            seeded_issues: number;
            /** Simulated */
            simulated: boolean;
        };
        /** IssueOut */
        IssueOut: {
            /** Id */
            id: string;
            /** Repo */
            repo: string;
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** State */
            state: string;
            /** Labels */
            labels: string[];
            /** Compliance Driven */
            compliance_driven: boolean;
            /** Acceptance Criteria */
            acceptance_criteria: string[];
            /** Publisher Id */
            publisher_id: string;
            /** Publisher Name */
            publisher_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deadline */
            deadline?: string | null;
            proposal?: components["schemas"]["PriceProposalOut"] | null;
            escrow?: components["schemas"]["EscrowCommitment"] | null;
            claim?: components["schemas"]["Claim"] | null;
            submission?: components["schemas"]["Submission"] | null;
            review?: components["schemas"]["Review"] | null;
            /** Contributor Id */
            contributor_id?: string | null;
            /** Paid Usdc */
            paid_usdc?: string | null;
            /** Github Url */
            github_url: string;
        };
        /** IssueSummaryOut */
        IssueSummaryOut: {
            /** Id */
            id: string;
            /** Repo */
            repo: string;
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** State */
            state: string;
            /** Labels */
            labels: string[];
            /** Compliance Driven */
            compliance_driven: boolean;
            /** Publisher Name */
            publisher_name: string;
            /** Price Usdc */
            price_usdc?: string | null;
            /** Confidence */
            confidence?: string | null;
            /** Deadline */
            deadline?: string | null;
            /** Github Url */
            github_url: string;
        };
        /**
         * LoopOut
         * @description The loop in public: what was funded, settled and paid, for one repository or
         *     all of them. No wallet and no transfer appears here.
         */
        LoopOut: {
            /** Repo */
            repo: string | null;
            /** Funded Open */
            funded_open: number;
            /** Settled Issues */
            settled_issues: number;
            /** Settled Issues 7D */
            settled_issues_7d: number;
            /** Matched Volume Usdc */
            matched_volume_usdc: string;
            /** Recent */
            recent: components["schemas"]["LoopSettlement"][];
        };
        /** LoopSettlement */
        LoopSettlement: {
            /** Issue Id */
            issue_id: string;
            /** Repo */
            repo: string;
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Amount */
            amount: {
                [key: string]: string | number;
            };
            /** Contributor */
            contributor: string;
            /**
             * Settled At
             * Format: date-time
             */
            settled_at: string;
            /** Github Url */
            github_url: string;
        };
        /**
         * MetricsOut
         * @description Every number is computed from the ledger and the lifecycle records (09).
         */
        MetricsOut: {
            /** Settled Issues */
            settled_issues: number;
            /**
             * Settled Issues 7D
             * @default 0
             */
            settled_issues_7d: number;
            /** Funded Issues Published */
            funded_issues_published: number;
            /**
             * Funded Issues 7D
             * @default 0
             */
            funded_issues_7d: number;
            /** Claim Rate 72H */
            claim_rate_72h: number;
            /** Acceptance Rate First Review */
            acceptance_rate_first_review: number;
            /** Repeat Publisher Rate */
            repeat_publisher_rate: number;
            /** Matched Volume Usdc */
            matched_volume_usdc: string;
            /** Median Hours To Payout */
            median_hours_to_payout: number | null;
            /**
             * Refund Rate
             * @default 0
             */
            refund_rate: number;
            /** Dispute Rate */
            dispute_rate: number;
            /** Publisher Overturn Rate */
            publisher_overturn_rate: number;
            /** Earners Over 500 Share */
            earners_over_500_share?: number | null;
            /** Top10 Payout Share */
            top10_payout_share?: number | null;
            /** Open Issues */
            open_issues: number;
            /** By State */
            by_state: {
                [key: string]: number;
            };
            /**
             * Reviews Issued
             * @default 0
             */
            reviews_issued: number;
            /** Median Review Seconds */
            median_review_seconds?: number | null;
            /** Median Review Cost Usdc */
            median_review_cost_usdc?: string | null;
        };
        /** PolicyRequest */
        PolicyRequest: {
            /** Approval Threshold Usdc */
            approval_threshold_usdc?: string | null;
            /** Approvers */
            approvers?: string[];
            /** Category Limits */
            category_limits?: {
                [key: string]: string;
            };
        };
        /** PriceProposalOut */
        PriceProposalOut: {
            /** Band Low */
            band_low: {
                [key: string]: string | number;
            };
            /** Band High */
            band_high: {
                [key: string]: string | number;
            };
            /** Recommended */
            recommended: {
                [key: string]: string | number;
            };
            /** Estimated Hours */
            estimated_hours: number;
            /**
             * Fundable
             * @default true
             */
            fundable: boolean;
            /** Complexity Score */
            complexity_score: number;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Signals */
            signals: {
                [key: string]: number;
            };
            /** Justification */
            justification: string;
            /** Comparables Note */
            comparables_note: string;
        };
        /** PublishRequest */
        PublishRequest: {
            /**
             * Repo
             * @example acme/ledger
             */
            repo: string;
            /** Number */
            number?: number | null;
            /** Title */
            title: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Labels */
            labels?: string[];
            /** Publisher Id */
            publisher_id: string;
            /**
             * Compliance Driven
             * @default false
             */
            compliance_driven: boolean;
            /** Signals */
            signals?: {
                [key: string]: number;
            };
        };
        /** Publisher */
        Publisher: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "company" | "maintainer";
            /**
             * Tier
             * @enum {string}
             */
            tier: "open" | "team" | "enterprise";
            wallet: components["schemas"]["Wallet"];
            /** Budget Remaining Usdc */
            budget_remaining_usdc: string;
            /** Approval Threshold Usdc */
            approval_threshold_usdc?: string | null;
            /** Approvers */
            approvers?: string[];
            /** Category Limits */
            category_limits?: {
                [key: string]: string;
            };
        };
        /**
         * ReputationEventOut
         * @description One settled issue's contribution to a contributor's standing.
         */
        ReputationEventOut: {
            /** Issue Id */
            issue_id: string;
            /** Repo */
            repo: string;
            /** Amount */
            amount: {
                [key: string]: string | number;
            };
            /** Points */
            points: number;
            /**
             * Settled At
             * Format: date-time
             */
            settled_at: string;
        };
        /**
         * Review
         * @description The platform's verdict on a submission.
         *
         *     The agent owns this record: there is no separate human verdict, and no draft
         *     to confirm. The publisher's remaining decision is whether to merge.
         */
        Review: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "accept" | "rework" | "reject";
            /** Findings */
            findings: string[];
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Head Sha */
            head_sha?: string | null;
            /** Reviewer */
            reviewer?: string | null;
            /** Seconds */
            seconds?: number | null;
            /** Cost Usdc */
            cost_usdc?: string | null;
        };
        /** SpendCategory */
        SpendCategory: {
            /** Label */
            label: string;
            /** Committed */
            committed: {
                [key: string]: string | number;
            };
            /** Released */
            released: {
                [key: string]: string | number;
            };
            /** Limit */
            limit?: {
                [key: string]: string | number;
            } | null;
        };
        /**
         * SpendOut
         * @description What an organisation budgeted, committed, released and can file (#50).
         */
        SpendOut: {
            /** Publisher Id */
            publisher_id: string;
            /** Name */
            name: string;
            /** Year */
            year: number;
            /** Budget Remaining */
            budget_remaining: {
                [key: string]: string | number;
            };
            /** Committed Held */
            committed_held: {
                [key: string]: string | number;
            };
            /** Committed */
            committed: {
                [key: string]: string | number;
            };
            /** Released */
            released: {
                [key: string]: string | number;
            };
            /** Refunded */
            refunded: {
                [key: string]: string | number;
            };
            /** By Category */
            by_category: components["schemas"]["SpendCategory"][];
            /** Fileable */
            fileable: components["schemas"]["FileableItem"][];
        };
        /** StatementLine */
        StatementLine: {
            /**
             * Paid At
             * Format: date-time
             */
            paid_at: string;
            /** Issue Id */
            issue_id: string;
            /** Repo */
            repo: string;
            /** Issue Number */
            issue_number: number;
            /** Issue Title */
            issue_title: string;
            /** Counterparty Id */
            counterparty_id: string;
            /** Counterparty Name */
            counterparty_name: string;
            /** Amount */
            amount: {
                [key: string]: string | number;
            };
            /**
             * Currency
             * @default USDC
             * @constant
             */
            currency: "USDC";
            /** Chain */
            chain: string;
            /** Tx Hash */
            tx_hash: string | null;
        };
        /** Submission */
        Submission: {
            /** Pr Number */
            pr_number: number;
            /** Head Sha */
            head_sha: string;
            /** Checks Passed */
            checks_passed: boolean;
            /** Files Changed */
            files_changed: number;
            /** Additions */
            additions: number;
            /** Deletions */
            deletions: number;
        };
        /** TimelineEntry */
        TimelineEntry: {
            /** Id */
            id: string;
            /**
             * Actor
             * @enum {string}
             */
            actor: "agent" | "publisher" | "contributor" | "system";
            /** Action */
            action: string;
            /** Outcome */
            outcome: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cost Usdc */
            cost_usdc?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Wallet */
        Wallet: {
            /** Address */
            address: string;
            /**
             * Chain
             * @default arc-testnet
             */
            chain: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_issues_api_v1_issues_get: {
        parameters: {
            query?: {
                /** @description Filter by lifecycle state */
                state?: string | null;
                publisher_id?: string | null;
                compliance_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_api_v1_issues_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Any unique string, such as a UUID. Retries with the same key get the first response back for 24 hours instead of running again. */
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_issue_api_v1_issues__issue_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeline_api_v1_issues__issue_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_api_v1_issues__issue_id__advance_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Any unique string, such as a UUID. Retries with the same key get the first response back for 24 hours instead of running again. */
                "idempotency-key"?: string | null;
            };
            path: {
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueOut"];
                };
            };
            /** @description Illegal step, busy issue or refused by the escrow */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_api_v1_issues__issue_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Any unique string, such as a UUID. Retries with the same key get the first response back for 24 hours instead of running again. */
                "idempotency-key"?: string | null;
            };
            path: {
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueOut"];
                };
            };
            /** @description Illegal step, busy issue or refused by the escrow */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decline_api_v1_issues__issue_id__decline_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Any unique string, such as a UUID. Retries with the same key get the first response back for 24 hours instead of running again. */
                "idempotency-key"?: string | null;
            };
            path: {
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeclineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueOut"];
                };
            };
            /** @description Not awaiting the merge, or already declined once */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_release_api_v1_issues__issue_id__approve_release_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Any unique string, such as a UUID. Retries with the same key get the first response back for 24 hours instead of running again. */
                "idempotency-key"?: string | null;
            };
            path: {
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveReleaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueOut"];
                };
            };
            /** @description Not one of the organisation's named approvers */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No release is waiting for approval */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    loop_api_v1_loop_get: {
        parameters: {
            query?: {
                /** @description owner/name; every repository if empty */
                repo?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoopOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispute_api_v1_issues__issue_id__dispute_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Any unique string, such as a UUID. Retries with the same key get the first response back for 24 hours instead of running again. */
                "idempotency-key"?: string | null;
            };
            path: {
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueOut"];
                };
            };
            /** @description Nothing to dispute, or already disputed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_publishers_api_v1_publishers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Publisher"][];
                };
            };
        };
    };
    metrics_api_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsOut"];
                };
            };
        };
    };
    decisions_api_v1_decisions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_api_v1_demo_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    list_contributors_api_v1_contributors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributorProfile"][];
                };
            };
        };
    };
    reputation_api_v1_contributors__contributor_id__reputation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contributor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReputationEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    statement_api_v1_contributors__contributor_id__statements__year__get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
            };
            header?: never;
            path: {
                contributor_id: string;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnualStatement"];
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_policy_api_v1_publishers__publisher_id__policy_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publisher_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Publisher"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spend_api_v1_publishers__publisher_id__spend_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path: {
                publisher_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_v1_publishers__publisher_id__audit_get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
            };
            header?: never;
            path: {
                publisher_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditExport"];
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    describe_api_v1_webhooks_github_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    receive_api_v1_webhooks_github_post: {
        parameters: {
            query?: never;
            header?: {
                "x-hub-signature-256"?: string | null;
                "x-github-event"?: string | null;
                "x-github-delivery"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
